package com.ewoner.jcac_etc_questions.utilities.MCConverter;

import java.io.FilenameFilter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * 
 * MIT License
 * 
 * Copyright (c) 2022 Brion Lang
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 * 
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author student
 */
public class MainFrame extends javax.swing.JFrame {

    MCModel model;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    MainFrame( MCModel newModel ) {
        this();
        model = newModel;
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter( new FileNameExtensionFilter( "ETC Question File (xml)", "xml" ) );
        model.setFc( fc );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        filePanel = new javax.swing.JPanel();
        fileLabel = new javax.swing.JLabel();
        fileTextBox = new javax.swing.JTextField();
        fileButton = new javax.swing.JButton();
        saveFielPanel = new javax.swing.JPanel();
        saveFileLabel = new javax.swing.JLabel();
        saveFileTextBox = new javax.swing.JTextField();
        saveFileButton = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();
        inforTextAreaScrollPane = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        convertButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        topPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        topPanel.setLayout(new javax.swing.BoxLayout(topPanel, javax.swing.BoxLayout.Y_AXIS));

        fileLabel.setText("File to Convert:");
        fileLabel.setMaximumSize(new java.awt.Dimension(98, 17));
        fileLabel.setMinimumSize(new java.awt.Dimension(98, 17));
        filePanel.add(fileLabel);

        fileTextBox.setEditable(false);
        fileTextBox.setColumns(25);
        filePanel.add(fileTextBox);

        fileButton.setBackground(new java.awt.Color(204, 204, 204));
        fileButton.setText("Open File");
        fileButton.setMaximumSize(new java.awt.Dimension(106, 23));
        fileButton.setMinimumSize(new java.awt.Dimension(106, 23));
        fileButton.setPreferredSize(new java.awt.Dimension(106, 23));
        fileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonActionPerformed(evt);
            }
        });
        filePanel.add(fileButton);

        topPanel.add(filePanel);

        saveFileLabel.setText("Save Filename:");
        saveFielPanel.add(saveFileLabel);

        saveFileTextBox.setEditable(false);
        saveFileTextBox.setColumns(25);
        saveFielPanel.add(saveFileTextBox);

        saveFileButton.setBackground(new java.awt.Color(204, 204, 204));
        saveFileButton.setText("Save as");
        saveFileButton.setMaximumSize(new java.awt.Dimension(106, 23));
        saveFileButton.setMinimumSize(new java.awt.Dimension(106, 23));
        saveFileButton.setName(""); // NOI18N
        saveFileButton.setPreferredSize(new java.awt.Dimension(106, 23));
        saveFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileButtonActionPerformed(evt);
            }
        });
        saveFielPanel.add(saveFileButton);

        topPanel.add(saveFielPanel);

        getContentPane().add(topPanel);

        bottomPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204)));
        bottomPanel.setLayout(new java.awt.BorderLayout());

        infoTextArea.setColumns(20);
        infoTextArea.setRows(5);
        inforTextAreaScrollPane.setViewportView(infoTextArea);

        bottomPanel.add(inforTextAreaScrollPane, java.awt.BorderLayout.CENTER);

        convertButton.setBackground(new java.awt.Color(204, 204, 204));
        convertButton.setText("Convert Questions");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });
        bottomPanel.add(convertButton, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(bottomPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonActionPerformed
        model.changeFile();
        this.fileTextBox.setText( model.getFileName() );
        this.saveFileTextBox.setText( model.getSaveFileName() );
    }//GEN-LAST:event_fileButtonActionPerformed

    private void saveFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileButtonActionPerformed
        model.changeSaveFile();
        this.saveFileTextBox.setText( model.getSaveFileName() );
    }//GEN-LAST:event_saveFileButtonActionPerformed

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        model.convertFile();

    }//GEN-LAST:event_convertButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
                if( "Nimbus".equals( info.getName() ) ) {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        } catch( ClassNotFoundException ex ) {
            java.util.logging.Logger.getLogger( MainFrame.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch( InstantiationException ex ) {
            java.util.logging.Logger.getLogger( MainFrame.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch( IllegalAccessException ex ) {
            java.util.logging.Logger.getLogger( MainFrame.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch( javax.swing.UnsupportedLookAndFeelException ex ) {
            java.util.logging.Logger.getLogger( MainFrame.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {
                new MainFrame().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton convertButton;
    private javax.swing.JButton fileButton;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JPanel filePanel;
    private javax.swing.JTextField fileTextBox;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JScrollPane inforTextAreaScrollPane;
    private javax.swing.JPanel saveFielPanel;
    private javax.swing.JButton saveFileButton;
    private javax.swing.JLabel saveFileLabel;
    private javax.swing.JTextField saveFileTextBox;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
